# Generated by Django 2.2.4 on 2019-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='publish',
        ),
        migrations.AlterField(
            model_name='newpost',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('housing', 'Housing'), ('house_owner', 'House Ownder')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
