# Generated by Django 2.2.4 on 2019-08-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_crm', '0003_newpost_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='newpost',
            name='user',
        ),
    ]
